name: Build WPF App

on:
  workflow_dispatch:      # omogućava ručno pokretanje
  pull_request:           # pokreće se kad student otvori PR
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Publish app
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # automatski koristi GitHub korisničko ime studenta
        name: ${{ github.actor }} - Paperless-WPF-Client
        path: ./publish
        # artefakt se automatski briše nakon 7 dana (umjesto 90)
        retention-days: 7
